
server:
  port: 8088

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/concessionaria_veiculos
    username: postgres
    password: adminfiap